using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;
using System.Collections;

public class SplashFade : MonoBehaviour {

    public Image splashImage;
    public string loadLevel;

	// Use this for initialization
	IEnumerator Start () {

        splashImage.canvasRenderer.SetAlpha(0.0f);

        FadeIn();
        yield return new WaitForSeconds(2.5f);
        FadeOut();
        yield return new WaitForSeconds(2.5f);
        SceneManager.LoadScene(loadLevel);

	
	}

    void FadeIn()
    {
        splashImage.CrossFadeAlpha(1.0f, 1.5f, false);

    }

    void FadeOut()
    {
        splashImage.CrossFadeAlpha(0.0f, 2.5f, false);
    }
	
	// Update is called once per frame
	void Update () {
	
	}
}
